version: "3.8"
services:
  nuxt:
    build:
      context: .
    image: lukiuwuxyz:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3011:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - CRYPTOBOT_TOKEN=
      - CLOUDTIPS_LAYOUTID=
      - NOWPAYMENTS_TOKEN=
      - ROCKET_TOKEN=
      - BOT_TOKEN=