version: "3.8"
services:
  nuxt:
    build:
      context: .
    image: lukiuwuxyz:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000